### ISSUE TITLE
Text transforms should "usually" return native strings

### ISSUE THREAD

**Issue by ale-rt** [plone/Products.PortalTransforms#37]
The current interface says "usually a string": https://github.com/plone/Products.PortalTransforms/blob/21af9be0460e7e7218dc6b25e57b038729789dc2/Products/PortalTransforms/interfaces.py#L12

The Python 3 porting PR #35 changed the returned value to text.

See also: https://community.plone.org/t/products-portaltransforms-data-datastream-getdata-changes/7373

**Comment by ale-rt** [comment]
Probably also #36 was a change needed to fix the fact that on Py3 we are now returning unicode.

**Comment by hvelarde** [comment]
@plone/release-team can we have a new release with this fix? seems others are having this issue on their sites.

**Comment by esteele** [comment]
@hvelarde Released as 3.1.5

**Comment by mauritsvanrees** [comment]
For the record, I am seeing this problem too on Plone 5.1.4 when viewing a document that was migrated from Plone 4 with transmogrifier (automatically turning ATDocument into a plone.app.contenttypes dexterity Document). Problem was that the text field contained `<html`, which meant `utils.body_finder` was called on it, which turned it into unicode since version 3.1.4.
I confirm that 3.1.5 fixes it, so thanks!
